#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class CourseManagementSystemDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  #endregion
	
	public CourseManagementSystemDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public CourseManagementSystemDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CourseManagementSystemDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CourseManagementSystemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CourseManagementSystemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Student> Student
	{
		get
		{
			return this.GetTable<Student>();
		}
	}
	
	public System.Data.Linq.Table<Course> Course
	{
		get
		{
			return this.GetTable<Course>();
		}
	}
	
	public System.Data.Linq.Table<Customer> Customer
	{
		get
		{
			return this.GetTable<Customer>();
		}
	}
	
	public System.Data.Linq.Table<Score> Score
	{
		get
		{
			return this.GetTable<Score>();
		}
	}
	
	public System.Data.Linq.Table<TeaClaI> TeaClaI
	{
		get
		{
			return this.GetTable<TeaClaI>();
		}
	}
	
	public System.Data.Linq.Table<TeaClaInfo> TeaClaInfo
	{
		get
		{
			return this.GetTable<TeaClaInfo>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
public partial class Student
{
	
	private int _SId;
	
	private string _Name;
	
	private string _Dept;
	
	private string _Class;
	
	public Student()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SId", DbType="Int NOT NULL")]
	public int SId
	{
		get
		{
			return this._SId;
		}
		set
		{
			if ((this._SId != value))
			{
				this._SId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(10)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept", DbType="NChar(10)")]
	public string Dept
	{
		get
		{
			return this._Dept;
		}
		set
		{
			if ((this._Dept != value))
			{
				this._Dept = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="NChar(10)")]
	public string Class
	{
		get
		{
			return this._Class;
		}
		set
		{
			if ((this._Class != value))
			{
				this._Class = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Course")]
public partial class Course
{
	
	private string _Course1;
	
	private string _CId;
	
	private string _STime;
	
	private System.Nullable<int> _SCredits;
	
	private string _TeachTime;
	
	private string _Dept;
	
	private string _TId;
	
	public Course()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Course", Storage="_Course1", DbType="NChar(10)")]
	public string Course1
	{
		get
		{
			return this._Course1;
		}
		set
		{
			if ((this._Course1 != value))
			{
				this._Course1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CId", DbType="NChar(10)")]
	public string CId
	{
		get
		{
			return this._CId;
		}
		set
		{
			if ((this._CId != value))
			{
				this._CId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STime", DbType="NChar(10)")]
	public string STime
	{
		get
		{
			return this._STime;
		}
		set
		{
			if ((this._STime != value))
			{
				this._STime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCredits", DbType="Int")]
	public System.Nullable<int> SCredits
	{
		get
		{
			return this._SCredits;
		}
		set
		{
			if ((this._SCredits != value))
			{
				this._SCredits = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeachTime", DbType="NChar(10)")]
	public string TeachTime
	{
		get
		{
			return this._TeachTime;
		}
		set
		{
			if ((this._TeachTime != value))
			{
				this._TeachTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept", DbType="NChar(10)")]
	public string Dept
	{
		get
		{
			return this._Dept;
		}
		set
		{
			if ((this._Dept != value))
			{
				this._Dept = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TId", DbType="NChar(10)")]
	public string TId
	{
		get
		{
			return this._TId;
		}
		set
		{
			if ((this._TId != value))
			{
				this._TId = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
public partial class Customer
{
	
	private System.Nullable<int> _pwd;
	
	private System.Nullable<int> _cId;
	
	public Customer()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="Int")]
	public System.Nullable<int> pwd
	{
		get
		{
			return this._pwd;
		}
		set
		{
			if ((this._pwd != value))
			{
				this._pwd = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cId", DbType="Int")]
	public System.Nullable<int> cId
	{
		get
		{
			return this._cId;
		}
		set
		{
			if ((this._cId != value))
			{
				this._cId = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Score")]
public partial class Score
{
	
	private System.Nullable<int> _SId;
	
	private string _CId;
	
	private string _Score1;
	
	public Score()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SId", DbType="Int")]
	public System.Nullable<int> SId
	{
		get
		{
			return this._SId;
		}
		set
		{
			if ((this._SId != value))
			{
				this._SId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CId", DbType="NChar(10)")]
	public string CId
	{
		get
		{
			return this._CId;
		}
		set
		{
			if ((this._CId != value))
			{
				this._CId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Score", Storage="_Score1", DbType="NChar(10)")]
	public string Score1
	{
		get
		{
			return this._Score1;
		}
		set
		{
			if ((this._Score1 != value))
			{
				this._Score1 = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TeaClaI")]
public partial class TeaClaI
{
	
	private string _Dept;
	
	private string _CId;
	
	private string _Teacher;
	
	private string _Coursename;
	
	public TeaClaI()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept", DbType="VarChar(255)")]
	public string Dept
	{
		get
		{
			return this._Dept;
		}
		set
		{
			if ((this._Dept != value))
			{
				this._Dept = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CId", DbType="VarChar(255)")]
	public string CId
	{
		get
		{
			return this._CId;
		}
		set
		{
			if ((this._CId != value))
			{
				this._CId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher", DbType="VarChar(255)")]
	public string Teacher
	{
		get
		{
			return this._Teacher;
		}
		set
		{
			if ((this._Teacher != value))
			{
				this._Teacher = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coursename", DbType="VarChar(255)")]
	public string Coursename
	{
		get
		{
			return this._Coursename;
		}
		set
		{
			if ((this._Coursename != value))
			{
				this._Coursename = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TeaClaInfo")]
public partial class TeaClaInfo
{
	
	private string _Dept;
	
	private string _CId;
	
	private string _Teacher;
	
	private string _CourseName;
	
	public TeaClaInfo()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept", DbType="VarChar(255)")]
	public string Dept
	{
		get
		{
			return this._Dept;
		}
		set
		{
			if ((this._Dept != value))
			{
				this._Dept = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CId", DbType="VarChar(255)")]
	public string CId
	{
		get
		{
			return this._CId;
		}
		set
		{
			if ((this._CId != value))
			{
				this._CId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher", DbType="VarChar(255)")]
	public string Teacher
	{
		get
		{
			return this._Teacher;
		}
		set
		{
			if ((this._Teacher != value))
			{
				this._Teacher = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseName", DbType="VarChar(255)")]
	public string CourseName
	{
		get
		{
			return this._CourseName;
		}
		set
		{
			if ((this._CourseName != value))
			{
				this._CourseName = value;
			}
		}
	}
}
#pragma warning restore 1591
